config/routes.rb
Rails.application.routes.draw do
  resources :trips
  root 'trips#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
    validates :arrive_date, :return_date, :destination, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :set_trip, only: [:show, :edit, :update, :destroy]

    def index
        @trips = Trip.all
        @trips = @trips.sort_by {|obj| obj.arrive_date }
    end

    def show
    end

    def new
        @trip = Trip.new()
    end

    def edit
    end

     def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created! Woohoo!' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

    def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated! Heck yeah!' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed. Mwahahahaha' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.fetch(:trip, {}).permit(:destination, :arrive_date ,:notes, :return_date)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trip_helper.rb
module TripHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirplaneProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form.label(:destination, "Destination:") %>
  <%= form.text_field(:destination) %>
 <%= form.label(:arrive_date, "Arrival Date:") %>
  <%= form.date_field(:arrive_date) %>
 <%= form.label(:return_date, "Return Date:") %>
  <%= form.date_field(:return_date) %>
 <%= form.label(:notes, "Notes:") %>
  <%= form.text_field(:notes) %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
html {
    min-height: 100%; /* This is required to ensure that the gradient stretches across the whole page */
}

body { #sky blue
    background: -webkit-linear-gradient(#33C7FF, #D2F3FF);
    background: -o-linear-gradient(#33C7FF, #D2F3FF);
    background: -moz-linear-gradient(#33C7FF, #D2F3FF);
    background: linear-gradient(#33C7FF, #D2F3FF);
    background-color: #93B874;

}
</style>
</head>
<body>
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Cancel', trips_path %>

</body>
</html>

app/views/trips/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
html {
    min-height: 100%; /* This is required to ensure that the gradient stretches across the whole page */
}

body { #green
    background: -webkit-linear-gradient(#24FB80, #BEFFDA);
    background: -o-linear-gradient(#24FB80, #BEFFDA);
    background: -moz-linear-gradient(#24FB80, #BEFFDA);
    background: linear-gradient(#24FB80, #BEFFDA);
    background-color: #93B874;

}
h1 {
    text-align: center;
    font-family:Impact;
    color: blue;
    font-size: 500%;
}

h2{
  text-align: center;
  font-size: 300%
}
table{

  margin-left: auto;
  margin-right: auto;
  background-color: whitesmoke;
  width: 80%;
  text-align: center;
  font-size = 150%

}
h3{
  text-align: center;
}
</style>
  <h1> Trips I've Taken This Year! </h1>
</head>
<body>
<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Arrival Date</th>
      <th>Return Date</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td> <%=trip.destination %>  </td>
        <td>  <%=trip.arrive_date %> </td>
        <td> <%=trip.return_date %>  </td>
        <td> <%= trip.notes %> </td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>
<%= link_to 'Add a New Trip', new_trip_path %>
</h3>
</body>
</html>

app/views/trips/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
html {
    min-height: 100%; /* This is required to ensure that the gradient stretches across the whole page */
}

body { #purple
    background: -webkit-linear-gradient(#922EFD, #E7D1FF);
    background: -o-linear-gradient(#922EFD, #E7D1FF);
    background: -moz-linear-gradient(#922EFD, #E7D1FF);
    background: linear-gradient(#922EFD, #E7D1FF);
    background-color: ##922EFD

}
</style>
</head>
<body>

<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

</body>
</html>

app/views/trips/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
html {
    min-height: 100%; /* This is required to ensure that the gradient stretches across the whole page */
}

body { #pink
    background: -webkit-linear-gradient(#FF1C76, #FECDE1);
    background: -o-linear-gradient(#FF1C76, #FECDE1);
    background: -moz-linear-gradient(#FF1C76, #FECDE1);
    background: linear-gradient(#FF1C76, #FECDE1);
    background-color: #93B874;

}
</style>
</head>
<body>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>

</body>
</html>